version: '3'

services:
  client:
    build: ./client
    environment:
      - NEXT_PUBLIC_WEBSOCKET_SERVER_URL=ws://localhost:8081
    tty: true
    # command: pnpm dev
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    tty: true
    # command: go run main.go
    volumes:
      - ./server:/app
    ports:
      - "8081:8080"
