name: E2E Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    defaults:
      run:
        working-directory: e2e-test
    steps:
    - uses: actions/checkout@v3
    - name: start application
      run: |
        cd ../
        chmod -R 777 client/
        docker compose up -d
        docker compose exec client yarn
        docker compose exec client yarn build
        docker compose exec client yarn hosting &
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm install -g yarn && yarn
    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps
    - name: Run Playwright tests
      run: yarn playwright test
    - name: Set up bot comment
      id: bot_comment
      run: |
        lf='\n'
        message="Playwright has finished executiong :tada:"
        message+="${lf}${lf}Here is the screenshot image:"
        echo "message=${message}" >> $GITHUB_OUTPUT
    - name: upload screenshot
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: screenshot
        path: e2e-test/tmp/chromium.png
        retention-days: 30
        if-no-files-found: error
    - name: Comment opening announce
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const imageFilePath = 'e2e-test/tmp/chromium.png';
          const imageData = fs.readFileSync(imageFilePath);
          const imageBase64 = Buffer.from(imageData).toString('base64');
          const params = {
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            body: '${{ steps.bot_comment.outputs.message }}',
            data: imageBase64
          }
          await github.rest.issues.createComment(params)
