name: E2E Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: e2e-test
    steps:
    - uses: actions/checkout@v3
    - name: start application
      run: |
        cd ../
        chmod -R 777 client/
        docker compose up -d
        docker compose exec client yarn
        docker compose exec client yarn build
        docker compose exec client yarn start &
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm install -g yarn && yarn
    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps
    - name: Run Playwright tests
      run: yarn playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: e2e-test/playwright-report/
        retention-days: 30
